import cv2 as cv
filepath="Ch2-images/child_3.jpg"
img=cv.imread(filepath,0)
h,w=img.shape
img_nn=cv.resize(src=img,dsize=(2*h,2*w),interpolation=cv.INTER_NEAREST)
img_area=cv.resize(src=img,dsize=(2*h,2*w),interpolation=cv.INTER_AREA)
img_bits=cv.resize(src=img,dsize=(2*h,2*w),interpolation=cv.INTER_BITS)
img_bits2=cv.resize(src=img,dsize=(2*h,2*w),interpolation=cv.INTER_BITS2)
img_cubic=cv.resize(src=img,dsize=(2*h,2*w),interpolation=cv.INTER_CUBIC)
img_lanczos4=cv.resize(src=img,dsize=(2*h,2*w),interpolation=cv.INTER_LANCZOS4)
img_linear=cv.resize(src=img,dsize=(2*h,2*w),interpolation=cv.INTER_LINEAR)
img_linear_exact=cv.resize(src=img,dsize=(2*h,2*w),interpolation=cv.INTER_LINEAR_EXACT)
#img_max=cv.resize(src=img,dsize=(2*h,2*w),interpolation=cv.INTER_MAX)
#img_tab_size=cv.resize(src=img,dsize=(2*h,2*w),interpolation=cv.INTER_TAB_SIZE)
#img_tab_size2=cv.resize(src=img,dsize=(2*h,2*w),interpolation=cv.INTER_TAB_SIZE2)

cv.imshow("The child",img)
cv.imshow("Interpolated - NN",img_nn)
cv.imshow("Interpolated - Area",img_area)
cv.imshow("Interpolated - Bits",img_bits)
cv.imshow("Interpolated - Bits2",img_bits2)
cv.imshow("Interpolated - Cubic",img_cubic)
cv.imshow("Interpolated - Lanczos4",img_lanczos4)
cv.imshow("Interpolated - Linear",img_linear)
cv.imshow("Interpolated - Linear_Exact",img_linear_exact)
#cv.imshow("Interpolated - Bits2",img_max)
#cv.imshow("Interpolated - Bits2",img_tab_size)
#cv.imshow("Interpolated - Bits2",img_tab_size2)
cv.waitKey(0)
